language: cpp
compiler:
  - gcc
before_script:
  - sudo apt-get install libglew1.5 libglew1.5-dev -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - wget http://www.sfml-dev.org/download/sfml/2.1/SFML-2.1-linux-gcc-64bits.tar.bz2
  - tar -xvf SFML-2.1-linux-gcc-64bits.tar.bz2
  - sudo cp -r SFML-2.1/* /usr/local/
  - cmake CMakeLists.txt
script:
  - make
branches:
  only:
    - master
