language: cpp
compiler:
  - gcc
before_script:
  - wget http://www.sfml-dev.org/download/sfml/2.1/SFML-2.1-linux-gcc-32bits.tar.bz2
  - tar -xvf SFML-2.1-linux-gcc-32bits.tar.bz2
  - sudo cp -r SFML-2.1/* /usr/local/
  - cmake CMakeLists.txt
script:
  - make
branches:
  only:
    - master
